name: "Spiced CUDA Build Action"
description: "Set up CUDA, verify prerequisites, build and package spiced with models and CUDA support."
inputs:
  cuda-version:
    description: "The CUDA version to install"
    required: true
    default: "12.4.1"
  cuda-compute-capability:
    description: "The CUDA compute capability to target"
    required: true
  artifact-tag:
    description: "Tag artifacts, generally os/hardware dependent e.g. 'linux_x86_64' or 'windows_aarch64'"
    required: true
  target_os:
    description: "operating system to target"
    required: true

outputs:
  artifact-name:
    description: "The name of the uploaded artifact"
    value: "spiced_models_cuda_${{ inputs.target-os }}_${{ inputs.target-arch }}.tar.gz"

runs:
  using: "composite"
  steps:
    - name: Define Shell and Commands (windows)
      if: ${{ inputs.target_os == 'windows'}}
      run: |
        echo "SHELL=pwsh" >> $GITHUB_ENV
        echo "BUILD_CMD=cd bin\\spiced && make SPICED_NON_DEFAULT_FEATURES='models,cuda'" >> $GITHUB_ENV
        echo "PACKAGE_CMD=move target\\release\\spiced.exe spiced.exe && tar -czf spiced_models_cuda_${{ inputs.cuda-compute-capability }}_${{ inputs.artifact-tag }}.tar.gz spiced.exe" >> $GITHUB_ENV
      shell: pwsh
    - name: Define Shell and Commands
      if: ${{ inputs.target_os != 'windows'}}
      run: |
        echo "SHELL=bash" >> $GITHUB_ENV
        echo "BUILD_CMD=make -C bin/spiced SPICED_NON_DEFAULT_FEATURES='models,cuda'" >> $GITHUB_ENV
        echo "PACKAGE_CMD=mv target/release/spiced spiced && chmod +x spiced && tar czf spiced_models_cuda_${{ inputs.cuda-compute-capability }}_${{ inputs.artifact-tag }}.tar.gz spiced" >> $GITHUB_ENV
      shell: bash

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.19
      id: cuda-toolkit
      with:
        cuda: ${{ inputs.cuda-version }}
        method: "network"
        use-github-cache: false
        non-cuda-sub-packages: '["libcurand-dev", "libcublas","libcublas-dev"]'
        sub-packages: '["nvcc","compiler","libraries","libraries-dev","cudart","cudart-dev"]'

    - name: Verify CUDA prerequisites
      run: |
        nvidia-smi
        nvcc --version
      shell: ${{ env.SHELL }}

    - name: Build spiced (models, cuda)
      env:
          CUDA_COMPUTE_CAP: ${{ inputs.cuda-compute-capability }}
      run: ${{ env.BUILD_CMD }}
      shell: ${{ env.SHELL }}

    - name: Package binary
      run: ${{ env.PACKAGE_CMD }}
      shell: ${{ env.SHELL }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spiced_models_cuda_${{ inputs.cuda-compute-capability }}_${{ inputs.artifact-tag }}
        path: spiced_models_cuda_${{ inputs.cuda-compute-capability }}_${{ inputs.artifact-tag }}.tar.gz

    - name: Set output artifact name
      run: echo "artifact-name=spiced_models_cuda_${{ inputs.cuda-compute-capability }}${{ inputs.artifact-tag }}" >> $GITHUB_ENV
      shell: bash
