name: throughput tests

on:
  workflow_dispatch:
    inputs:
      spiced_commit:
        description: 'spiced build commit'
        required: false
        type: string
      spicepod_path:
        description: 'The spicepod file to test with'
        required: true
        type: string
      query_set:
        description: 'Query set'
        required: true
        default: 'tpch'
        type: choice
        options:
          - 'tpch'
          - 'tpcds'
          - 'clickbench'

jobs:
  run-throughput:
    name: Run throughput test
    runs-on: spiceai-runners
    steps:
      - uses: actions/checkout@v4

      - name: Install MinIO
        run: |
          sudo apt update && sudo apt install wget -y
          sudo wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc
          sudo chmod +x /usr/local/bin/mc
          mc alias set spice-minio ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Set testoperator commit
        run: |
          echo "TESTOPERATOR_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Download the testoperator from MinIO if it exists
        run: |
          sudo mkdir -p /usr/local/bin
          if mc stat spice-minio/artifacts/testoperator/linux-x86_64/$TESTOPERATOR_COMMIT/testoperator; then
            mc cp spice-minio/artifacts/testoperator/linux-x86_64/$TESTOPERATOR_COMMIT/testoperator ./testoperator
            sudo cp ./testoperator /usr/local/bin/testoperator
            sudo chmod +x /usr/local/bin/testoperator
            echo "TESTOPERATOR_DOWNLOADED=true" >> $GITHUB_ENV
          else
            echo "TESTOPERATOR_DOWNLOADED=false" >> $GITHUB_ENV
          fi

      - name: Setup Rust
        if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
        uses: ./.github/actions/setup-rust
        with:
          os: 'linux'
      
      - name: Setup cc
        if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
        uses: ./.github/actions/setup-cc

      - name: Get latest trunk commit
        if: ${{ !github.event.inputs.spiced_commit }}
        run: |
          git fetch origin
          echo "SPICED_COMMIT=$(git rev-parse origin/trunk)" >> $GITHUB_ENV
      
      - name: Set SPICED_COMMIT from workflow input
        if: ${{ github.event.inputs.spiced_commit }}
        run: |
          echo "SPICED_COMMIT=${{ github.event.inputs.spiced_commit }}" >> $GITHUB_ENV
      
      - name: Download spiced from MinIO
        run: |
          mc cp spice-minio/artifacts/spiced/linux-x86_64/$SPICED_COMMIT/spiced_models_linux_x86_64.tar.gz spiced_models_linux_x86_64.tar.gz
          tar -xzf spiced_models_linux_x86_64.tar.gz
          sudo cp ./spiced /usr/local/bin/spiced

      - name: Build the testoperator if it wasn't downloaded
        if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
        run: |
          cargo build -p testoperator --release
          sudo cp target/release/testoperator /usr/local/bin/testoperator
          sudo chmod +x /usr/local/bin/testoperator
      
      - name: Prepare file-based data directory
        run: |
          sudo rm -rf /opt/spiced/data
          sudo mkdir -p /opt/spiced/data
          sudo chown runner:runner -R /opt/spiced/data

      - name: Download File Connector TPCH Data
        if: ${{ github.event.inputs.query_set == 'tpch' }}
        run: |
          cd /opt/spiced/data
          mc cp spice-minio/benchmarks/tpch_sf1/customer/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/lineitem/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/nation/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/orders/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/part/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/partsupp/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/region/ ./ --recursive
          mc cp spice-minio/benchmarks/tpch_sf1/supplier/ ./ --recursive
      
      - name: Download File Connector TPCDS Data
        if: ${{ github.event.inputs.query_set == 'tpcds' }}
        run: |
          cd /opt/spiced/data
          mc cp spice-minio/benchmarks/tpcds_sf1/catalog_sales/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/catalog_returns/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/inventory/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/store_sales/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/store_returns/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/web_sales/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/web_returns/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/customer/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/customer_address/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/customer_demographics/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/date_dim/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/household_demographics/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/item/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/promotion/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/store/ ./ --recursive
          mc cp spice-minio/benchmarks/tpcds_sf1/time_dim/ ./ --recursive
      
      - name: Run the throughput test
        run: |
          testoperator run throughput -s /usr/local/bin/spiced -p ${{ github.event.inputs.spicepod_path }} -d /opt/spiced/data --query-set ${{ github.event.inputs.query_set }}
        env:
          S3_ENDPOINT: ${{ secrets.CLICKBENCH_S3_ENDPOINT}}
          S3_KEY: ${{ secrets.CLICKBENCH_S3_KEY}}
          S3_SECRET: ${{ secrets.CLICKBENCH_S3_SECRET}}
      
      - name: Upload the testoperator binary
        if: ${{ env.TESTOPERATOR_DOWNLOADED != 'true' }}
        run: |
          mc cp /usr/local/bin/testoperator spice-minio/artifacts/testoperator/linux-x86_64/$TESTOPERATOR_COMMIT/testoperator